// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD-GDZyhwEem22QZHfXrbTqcz9V12B3rUY',
    appId: '1:244198641872:web:b78c53157484bac9ef4ed5',
    messagingSenderId: '244198641872',
    projectId: 'speciesdetection',
    authDomain: 'speciesdetection.firebaseapp.com',
    storageBucket: 'speciesdetection.firebasestorage.app',
    measurementId: 'G-EKCT5T3NZ8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBS9lIDdQwv0fAx0gRPWWDubxsFzI7lHQY',
    appId: '1:244198641872:android:28aa2c16fdefcb48ef4ed5',
    messagingSenderId: '244198641872',
    projectId: 'speciesdetection',
    storageBucket: 'speciesdetection.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCReJONq4JxhtQkYnBYSzt9PKrOWnBAjtE',
    appId: '1:244198641872:ios:c536613cc5299e30ef4ed5',
    messagingSenderId: '244198641872',
    projectId: 'speciesdetection',
    storageBucket: 'speciesdetection.firebasestorage.app',
    iosBundleId: 'com.example.speciesdectection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCReJONq4JxhtQkYnBYSzt9PKrOWnBAjtE',
    appId: '1:244198641872:ios:c536613cc5299e30ef4ed5',
    messagingSenderId: '244198641872',
    projectId: 'speciesdetection',
    storageBucket: 'speciesdetection.firebasestorage.app',
    iosBundleId: 'com.example.speciesdectection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD-GDZyhwEem22QZHfXrbTqcz9V12B3rUY',
    appId: '1:244198641872:web:c7e01e36e85ec672ef4ed5',
    messagingSenderId: '244198641872',
    projectId: 'speciesdetection',
    authDomain: 'speciesdetection.firebaseapp.com',
    storageBucket: 'speciesdetection.firebasestorage.app',
    measurementId: 'G-7PHJGJT5W1',
  );
}
