// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA6fxyMPYai-gePCrWMvvqjDBig939Rf-s',
    appId: '1:611693981412:web:ba7ce43424f9cce014c6f1',
    messagingSenderId: '611693981412',
    projectId: 'speciesdetection-d064a',
    authDomain: 'speciesdetection-d064a.firebaseapp.com',
    storageBucket: 'speciesdetection-d064a.firebasestorage.app',
    measurementId: 'G-42GGJSQSCX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBhLstZb6AuCpZsO6mt8iliUWVQN5XD_Ac',
    appId: '1:611693981412:android:4ab6fc7525eae97514c6f1',
    messagingSenderId: '611693981412',
    projectId: 'speciesdetection-d064a',
    storageBucket: 'speciesdetection-d064a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBlm8dEX5j2sCxb5Ya4J3DBoFQYgzsW8G8',
    appId: '1:611693981412:ios:ce3a9f07a2ef9b7714c6f1',
    messagingSenderId: '611693981412',
    projectId: 'speciesdetection-d064a',
    storageBucket: 'speciesdetection-d064a.firebasestorage.app',
    iosBundleId: 'com.example.speciesdectection',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBlm8dEX5j2sCxb5Ya4J3DBoFQYgzsW8G8',
    appId: '1:611693981412:ios:ce3a9f07a2ef9b7714c6f1',
    messagingSenderId: '611693981412',
    projectId: 'speciesdetection-d064a',
    storageBucket: 'speciesdetection-d064a.firebasestorage.app',
    iosBundleId: 'com.example.speciesdectection',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA6fxyMPYai-gePCrWMvvqjDBig939Rf-s',
    appId: '1:611693981412:web:efff07e4cbe2ab3e14c6f1',
    messagingSenderId: '611693981412',
    projectId: 'speciesdetection-d064a',
    authDomain: 'speciesdetection-d064a.firebaseapp.com',
    storageBucket: 'speciesdetection-d064a.firebasestorage.app',
    measurementId: 'G-D21MC6GD04',
  );

}